# TalentRanker Configuration File

# Data Processing Settings
data:
  directories:
    base_data_dir: "data"
    resumes:
      raw: "data/resumes/raw"
      markdown: "data/resumes/markdown"
      json: "data/resumes/json"
      sub: "data/resumes"
    job_descriptions:
      raw: "data/job_descriptions/raw"
      markdown: "data/job_descriptions/markdown"
      json: "data/job_descriptions/json"
      sub: "data/job_descriptions"
    rankings: "data/rankings"
    exports: "data/exports"

# Scoring Configuration
scoring:
  weights:
    job_title_relevance: 0.03
    experience_years_match: 0.20
    education_match: 0.20
    experience_relevance: 0.08
    skills_match: 0.20
    soft_skills_relevance: 0.04
    certifications_match: 0.05
    domain_knowledge_match: 0.04
    languages_match: 0.10
    preferred_education_relevance: 0.03
    preferred_qualifications_relevance: 0.03
  embedding_score: 0.5
  fuzzy_score: 0.5

# Model Configuration
models:
  sentence_transformer: "all-MiniLM-L6-v2"
  
  language_model:
    model_name: "gemini-2.5-flash"
    temperature: 0
    api_key: "${GOOGLE_API_KEY}"

# Processing Configuration
processing:
  batch_size: 10
  

# UI Configuration
ui:
  interface:
    server:
      host: "0.0.0.0"
      port: 7860
      share: false
      debug: true
  

# Default Values
defaults:
  no_data_score: -1
  missing_requirement_score: 50
  
